# python-exceptions task 3